import type { Metadata } from "next";
import { Anybody, Hanken_Grotesk, JetBrains_Mono } from "next/font/google";
import Navbar from '@/components/navigation/Navbar'
import Footer from '@/components/Footer'
import PageTransition from '@/components/motion/PageTransition'
import "./globals.css";

const anybody = Anybody({
    subsets: ["latin"],
    weight: ["700", "800"],
    variable: "--font-anybody",
});

const hankenGrotesk = Hanken_Grotesk({
    subsets: ["latin"],
    weight: ["400", "500"],
    variable: "--font-hanken",
});

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["600"],
    variable: "--font-jetbrains",
});
export const metadata: Metadata = {
    title: "Fit with Sai",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${anybody.variable} ${hankenGrotesk.variable} ${jetbrainsMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Navbar />
                <main>
                    <PageTransition>{children}</PageTransition>
                </main>
                <Footer />
            </body>
        </html>
    );
}